name: 'Report Test Coverage 📊'

on:
  pull_request:

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: yarn

      - run: yarn coverage

      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
